"""initial schema: users, patients, ecg_records, anomaly_events, audit_trails

Revision ID: 9840408bc1c5
Revises: 
Create Date: 2026-08-30 17:21:40.403309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9840408bc1c5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('bed_number', sa.String(length=32), nullable=True),
    sa.Column('admission_date', sa.DateTime(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('attending_doctor', sa.String(length=255), nullable=True),
    sa.Column('active_record_id', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_bed_number'), 'patients', ['bed_number'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'DOCTOR', 'NURSE', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_trails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_trails_timestamp'), 'audit_trails', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_trails_user_id'), 'audit_trails', ['user_id'], unique=False)
    op.create_table('ecg_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('physionet_record_id', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ecg_records_patient_id'), 'ecg_records', ['patient_id'], unique=False)
    op.create_table('anomaly_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('prediction_label', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('heatmap', sa.JSON(), nullable=True),
    sa.Column('r_peak_sample', sa.Integer(), nullable=True),
    sa.Column('timestamp_ms', sa.BigInteger(), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('review_status', sa.Enum('PENDING', 'APPROVED', 'CORRECTED', name='reviewstatus'), nullable=False),
    sa.Column('corrected_label', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['ecg_records.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_events_patient_id'), 'anomaly_events', ['patient_id'], unique=False)
    op.create_index(op.f('ix_anomaly_events_prediction_label'), 'anomaly_events', ['prediction_label'], unique=False)
    op.create_index(op.f('ix_anomaly_events_record_id'), 'anomaly_events', ['record_id'], unique=False)
    op.create_index(op.f('ix_anomaly_events_timestamp_ms'), 'anomaly_events', ['timestamp_ms'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anomaly_events_timestamp_ms'), table_name='anomaly_events')
    op.drop_index(op.f('ix_anomaly_events_record_id'), table_name='anomaly_events')
    op.drop_index(op.f('ix_anomaly_events_prediction_label'), table_name='anomaly_events')
    op.drop_index(op.f('ix_anomaly_events_patient_id'), table_name='anomaly_events')
    op.drop_table('anomaly_events')
    op.drop_index(op.f('ix_ecg_records_patient_id'), table_name='ecg_records')
    op.drop_table('ecg_records')
    op.drop_index(op.f('ix_audit_trails_user_id'), table_name='audit_trails')
    op.drop_index(op.f('ix_audit_trails_timestamp'), table_name='audit_trails')
    op.drop_table('audit_trails')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_patients_bed_number'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
